#Config version, do not change this
version: 1

#Write interval to refresh the query (in minutes)
interval: 3

#Do you want to add the server this plugin is running on slots?
add_self_slots: true

#Write your server IPs and ports like this:

# server.myip.com: 19132
#WARNING!!! If you write IP like this:
#server.myip.com:19132, plugin won't crash, but it won't change slots

servers:
 "play.example.com": 19132
 "my.server.net": 19754